version: '3'
services:
  influxdb:
    image: influxdb:1.4.3-alpine
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=ssl

  grafana:
    image: grafana/grafana:4.6.3
    ports:
      - "3000:3000"
    volumes:
      - "./data/grafana:/var/lib/grafana"
    links:
      - influxdb

#  chronograf:
#    image: chronograf:alpine
#    ports:
#      - "8888:8888"
#    links:
#      - influxdb